In [2]:
import numpy as np

In [13]:
## Start with a list (that has no shape)
my_list = [1,2,3]
print(my_list)
## Nota che la lista ha le sue virgole

[1, 2, 3]


In [14]:
## Convert the list to np.array
my_array = np.array(my_list)

In [ ]:
## General rule of reshape:
#0 means do not change this size
#-1 means infert it

In [6]:
print(my_array, my_array.shape)

[1 2 3] (3,)


In [11]:
my_array = my_array.reshape(-1,3)
print(my_array, my_array.shape)

[[1 2 3]] (1, 3)


In [15]:
my_array = my_array.reshape(3,)
print(my_array, my_array.shape)

my_array = my_array.reshape(3)
print(my_array, my_array.shape)

## (,3) NON è una valid shape

[1 2 3] (3,)
[1 2 3] (3,)


In [19]:
## Ok, quindi deduco che la logica della shape è "quanti elementi ci sono".
## Non esiste il concetto di vettore riga, colonna
## Esempio shape= (1,3) --> c'è un elemento che contiene 3 elementi: [[a b c]]

## Verifico la th:
test_list=[[1,2,3],[4,5,6]]
my_test_array = np.array(test_list)
print(my_test_array, my_test_array.shape) ## Mi aspetto (2,3) :)

print("***")
test_list=[ [[1,2,3],[3,4,5]] , [[5,6,7],[7,8,9]] ]
my_test_array = np.array(test_list)
print(my_test_array, my_test_array.shape) 
## Mi aspetto (2,2,3) :)
## Perché ho 2 elementi, ognuno dei quali contiene 2 elementi, ognuno dei quali contiene 3 elementi

[[1 2 3]
 [4 5 6]] (2, 3)
***
[[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]] (2, 2, 3)


In [ ]:
## Ganglioneuralgia sfenopalatina --> emicrania da freddo (quando mangi un gelato)