In [13]:
import numpy as np
### Imports (possibility number 1)
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.regularizers import L1L2
"""
## Imports (possibility number 2. They are equivalent)
from keras.models import Sequential
from keras.layers import Dense
from keras.regularizers import L1L2
"""

## I prefer, Imports #1 for didactical purposes as so you clearly see that
## keras is a front-end for tensorflow (which is the back-end)

"""
Prepare you data, such as:
"""
x_train = np.array([ [1,1],[1,2],[1,3], [4,1],[4,4],[4,5] ])  # should be a numpy array
y_train = np.array([ [0],[0],[0],[1],[1],[1] ])  # should be a numpy array

print(x_train)
print("****")
print(y_train)


"""
Set up the logistic regression model
"""
model = Sequential()
model.add(Dense(1,  # output dim is 1, probability of a certain_class
                activation='sigmoid',
                kernel_regularizer=L1L2(l1=0.0, l2=0.1),
                input_dim=len(x_train[0]))) #input_dim = number of input features you have
model.compile(optimizer='sgd',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

"""
Fit/Predict
"""
model.fit(x_train, y_train, epochs=2)
#model.fit(x_train, y_train, epochs=2, validation_data=(x_val, y_val))
model.predict(x_train)

          


[[1 1]
 [1 2]
 [1 3]
 [4 1]
 [4 4]
 [4 5]]
****
[[0]
 [0]
 [0]
 [1]
 [1]
 [1]]
Epoch 1/2
1/1 [==============================] - 0s 642us/step - loss: 0.1318 - accuracy: 0.5000
Epoch 2/2
1/1 [==============================] - 0s 661us/step - loss: 0.1313 - accuracy: 0.5000


array([[0.73536664],
       [0.89657104],
       [0.9643382 ],
       [0.6626425 ],
       [0.9835054 ],
       [0.9946525 ]], dtype=float32)